### ISSUE TITLE
Надо бы отрефакторить

### ISSUE THREAD

**Issue by jt3k** [jsqry/jsqry#1]
- [ ] Везде где необходимо нужно поменять `==` на `===` т.к. у последнего перформанс выше
- [x] в define заменить сравнение с undefined на оператор in (возможно не нужен вообще define)
- [ ] обернуть всё в нормальную UMD обёртку, чтобы и в ноде можно было юзить, и в ес6 и в рекваержсе, например.
- [x] для рефакторингов и доработок нужны тесты.

**Comment by jt3k** [comment]
просто закрыл ? 

То есть рефакторить не нужно?

**Comment by xonixx** [comment]
1. Менять == на === ради перформанса - экономия на спичках
2. Это пофиксил
3. Ну в ноде и сейчас можно, а остальное я не использую, поэтому пока не имею возможности нормально протестировать
4. Тесты есть: https://github.com/xonixx/jsqry/blob/master/spec.js

**Comment by jt3k** [comment]
3) ну так соопщество есть яж для этого ишьюс и сделал чтобы обсудить и запилить

**Comment by xonixx** [comment]
Ок, добавил #4
